# コード2.1
# name: Hello
# on: push
# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo  "Hello, world"
#       - uses: actions/checkout@v4

# コード2.4
# name: Manual
# on:
#   workflow_dispatch:
#     inputs:
#       greeting:
#         type: string
#         default: Hello
#         required: true
#         description: A cheerful word
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "${{ inputs.greeting }}"

# コード2.5
# name: Schedule
# on:
#   schedule:
#     - cron: '*/15 * * * *'
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     steps:
#       - run: date
# コード3.1
# name: Contexts
# on: push
# jobs:
#   print:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "${{ github.actor }}"
# コード3.2
# name: Environment variables
# on: push
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     env:
#       BRANCH: main
#     steps:
#       - run: echo "${BRANCH}"
#       - uses: actions/checkout@v4
#         with:
#           ref: ${{env.BRANCH}}
# コード3.3
# name: Override environment variables
# on: push
# env:
#   EXAMPLE: Defined by workflow level
# jobs:
#   print:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "${EXAMPLE}"
#       - env:
#           EXAMPLE: Defined by step level
#         run: echo "$EXAMPLE"
# コード3.4
# name: Intermediate environment variables
# on: push
# jobs:
#   print:
#     runs-on: ubuntu-latest
#     env:
#       ACTOR: ${{github.actor}}
#     steps:
#       - run: echo "${ACTOR}"
# コード3.5
name: Variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{vars.USERNAME}}
    steps:
      - run: echo "${USERNAME}"