# コード2.1
# name: Hello
# on: push
# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo  "Hello, world"
#       - uses: actions/checkout@v4

# コード2.4
# name: Manual
# on:
#   workflow_dispatch:
#     inputs:
#       greeting:
#         type: string
#         default: Hello
#         required: true
#         description: A cheerful word
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "${{ inputs.greeting }}"

# コード2.5
# name: Schedule
# on:
#   schedule:
#     - cron: '*/15 * * * *'
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     steps:
#       - run: date
# コード3.1
name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"